language: ruby

sudo: false

cache: bundler

env:
  global:
    # Improves JRuby startup time.
    # See https://github.com/jruby/jruby/wiki/Improving-startup-time
    - "JRUBY_OPTS=--dev"

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
#  - jruby-9.1.2.0 # TODO: Figure out why `bundle exec` can't find binaries

before_script:
  - git config --local user.email "travis@travis.ci"
  - git config --local user.name "Travis CI"

script:
  - bundle exec rspec
  - bundle exec overcommit --sign
  - bundle exec overcommit --run
